server:
  port: 9090

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database: mysql


cloud:
  auth-url: https://api-identity.infrastructure.cloud.toast.com/v2.0
  user-name: sjun0322@naver.com
  password: booklay1234
  tenant-id: fcb81f74e379456b8ca0e091d351a7af
  storage-url: https://api-storage.cloud.toast.com/v1/AUTH_fcb81f74e379456b8ca0e091d351a7af
  container: /booklay_storage/

booklay:
  secure:
    appkey: 500rMJPT021TnyNl
    db_username: 06bd87410af34cdabe826c117fb76771
    db_url: 0b22abcb84cf49e09f06fa3a29a919fe
    db_password: 314a5e5a46004ab593c84049d362f835
    url: https://api-keymanager.nhncloudservice.com/keymanager/v1.0/appkey/500rMJPT021TnyNl/secrets/
    p12_password: 1234
  pool_size: 2

  redis:
    port: 6379
    host: 127.0.0.1
    password:
    database: 0

  elasticsearch:
    uri: 133.186.210.108:9200
