server:
  port: 9090

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database: mysql

booklay:
  secure:
    appkey: REDACTED
    db_username: REDACTED
    db_url: REDACTED
    db_password: REDACTED
    url: https://api-keymanager.nhncloudservice.com/keymanager/v1.0/appkey/REDACTED/secrets/
  pool_size: 20