server:
  port: 9090

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database: mysql

  kafka:
    consumer:
      group-id: shop

  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB

cloud:
  auth-url: https://api-identity.infrastructure.cloud.toast.com/v2.0
  user-name: sjun0322@naver.com
  password: booklay1234
  tenant-id: fcb81f74e379456b8ca0e091d351a7af
  storage-url: https://api-storage.cloud.toast.com/v1/AUTH_fcb81f74e379456b8ca0e091d351a7af
  container: /booklay_storage/

booklay:
  gateway-origin: http://125.6.36.253:8080
  gw-url: http://125.6.36.253
  secure:
    appkey: 500rMJPT021TnyNl
    db_username: 06bd87410af34cdabe826c117fb76771
    db_url: 0b22abcb84cf49e09f06fa3a29a919fe
    db_password: 314a5e5a46004ab593c84049d362f835
    url: https://api-keymanager.nhncloudservice.com/keymanager/v1.0/appkey/500rMJPT021TnyNl/secrets/
    p12_password: 1234

  pool_size: 20

  redis:
    host: 133.186.151.141
    port: 6379
    database: 4
    password: "*N2vya7H@muDTwdNMR!"

  elasticsearch:
    uri: 133.186.210.108:9200

project:
  build:
    outputDirectory: output

message:
  topic:
    coupon:
      request: coupon-zone-request
      response: coupon-zone-response
